Rails/Output:
  Exclude:
    - db/seeds.rb

Metrics/BlockLength:
  Exclude:
    - config/application.rb
    - config/environments/*.rb
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb

# The authentication system in Rails has special handling for the find_by_password_reset_token! method.
# Trying to use find_by(password_reset_token: params[:token]) will fail.
Rails/DynamicFindBy:
  Exclude:
    - app/controllers/passwords_controller.rb
